// Build-time prerendering: renders every route to a static HTML file so the
// site ships fully-formed markup (good for SEO, crawlers and first paint) and
// the React bundle only hydrates it on the client.
//
// Runs after both Vite builds:
//   1. `vite build`                    -> dist/        (client assets + index.html template)
//   2. `vite build --ssr entry-server` -> dist-server/ (server render function)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const distDir = path.join(root, 'dist');

const template = fs.readFileSync(path.join(distDir, 'index.html'), 'utf-8');

if (!template.includes('<!--app-head-->') || !template.includes('<div id="root"></div>')) {
  throw new Error('index.html is missing the <!--app-head--> or <div id="root"></div> placeholders.');
}

const { render, routes } = await import(
  pathToFileURL(path.join(root, 'dist-server', 'entry-server.js')).href
);

function buildPage({ html, head }) {
  return template
    .replace('<!--app-head-->', head)
    .replace('<div id="root"></div>', `<div id="root">${html}</div>`);
}

// Prerender each known route to <route>/index.html (and / to index.html).
for (const url of routes) {
  const result = await render(url);
  const outPath =
    url === '/'
      ? path.join(distDir, 'index.html')
      : path.join(distDir, url, 'index.html');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, buildPage(result));
  console.log('prerendered', url);
}

// Prerender the catch-all NotFound route as 404.html — Netlify serves this
// (with a 404 status) for any path that has no matching file.
const notFound = await render('/__404__');
fs.writeFileSync(path.join(distDir, '404.html'), buildPage(notFound));
console.log('prerendered 404.html');

// Emit a `_headers` file into the publish folder so the security/cache headers
// apply on Netlify (works for both Netlify Drop and git deploys).
//
// IMPORTANT: do NOT put a netlify.toml in dist/ — when the dist folder is
// uploaded via Netlify Drop, a netlify.toml with a [build] section makes
// Netlify try to run a build inside the (source-less) folder, which fails.
// A `_headers` file only configures headers and never triggers a build.
const headers = `# Generated by scripts/prerender.mjs — do not edit by hand.
/*
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://maps.googleapis.com; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: https://*.googleapis.com https://*.gstatic.com; media-src 'self'; frame-src https://www.google.com https://maps.google.com; connect-src 'self'
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/*.webp
  Cache-Control: public, max-age=2592000

/*.mp4
  Cache-Control: public, max-age=31536000, immutable
`;
fs.writeFileSync(path.join(distDir, '_headers'), headers);
console.log('wrote dist/_headers');
